---
title: "Example htmlwidgets"
author: "SOUNDBoard Interest Group"
package: SOUNDBoard
runtime: shiny
output:
  html_document:
    css: soundboard2.css
vignette: >
  %\VignetteIndexEntry{Example htmlwidgets}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Examples of Interactive Graphics

## Using `htmlwidgets` for displaying tabular data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
suppressPackageStartupMessages({
    library(htmlwidgets)
    library(DT)
})
data("airquality")
data("mtcars")
```

```{r, results='asis'}
datatable(airquality, options = list(
    pageLength = 10
    # ,initComplete = JS(
    #     "function(settings, json) {",
    #     "$(this.api().table().header()).",
    #     "css({'background-color': '#43A2CA', 'padding': '4px', 'font-family': 'times'});",
    #     "}")
    ),
    class = "compact stripe hover",
    style = "default",
    # filter = "top",
    width = 800)
```

-----------------------------------------------------------------
## Using interactive plots with `plotly` and `ggplot2`

```{r}
suppressPackageStartupMessages({
    library(ggplot2)
    library(plotly)
})
mtcars$gear <- factor(mtcars$gear,levels=c(3,4,5),
  	labels=c("3gears","4gears","5gears")) 
mtcars$am <- factor(mtcars$am,levels=c(0,1),
  	labels=c("Automatic","Manual")) 
mtcars$cyl <- factor(mtcars$cyl,levels=c(4,6,8),
   labels=c("4cyl","6cyl","8cyl"))
p <- qplot(hp, mpg, data=mtcars, shape=am, color=am, 
   facets=gear~cyl, size=I(3),
   xlab="Horsepower", ylab="Miles per Gallon")
ggplotly(p, width = 518) %>%
    layout(margin = list(l = 130, r = 85))
```

